sudo: false
language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0-preview1
  - rbx-2
  - jruby-18mode
  - jruby-19mode
script: "bundle exec rake test"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  exclude:
    - rvm: jruby-18mode
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: ree
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/4.1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.1.gemfile
    - rvm: ree
      gemfile: gemfiles/4.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.1.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/4.2.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/4.2.gemfile
    - rvm: ree
      gemfile: gemfiles/4.2.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.2.gemfile
