language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
script: "bundle exec rake test"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile

matrix:
  # https://github.com/jruby/jruby/issues/573
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
